name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: System dependencies
      run: sudo apt install pkg-config libssl-dev zlib1g-dev
    - name: Cache
      uses: actions/cache@v2.1.1
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: target
        # An explicit key for restoring and saving the cache
        key: release
    - uses: actions/checkout@v2
    - name: Install Nightly
      run: rustup toolchain add nightly
    - name: Install semantic-rs
      run: cargo +nightly install --git https://github.com/etclabscore/semantic-rs --tag v2.12.1
    - name: Build
      run: cargo build --release --verbose
    - name: Semantic release
      run: semantic-rs
